
export const screenText = (index) => {
        const message = [ "P",
        "Pr",
        "Pro",
        "Prog",
        "Progr",
        "Progra",
        "Program",
        "Programm",
        "Programme",
        "Programmer\n\n",
        "Programmer\n\nD",
        "Programmer\n\nDe",
        "Programmer\n\nDev",
        "Programmer\n\nDeve",
        "Programmer\n\nDevel",
        "Programmer\n\nDevelo",
        "Programmer\n\nDevelop",
        "Programmer\n\nDevelope",
        "Programmer\n\nDeveloper",
        "Programmer\n\nDeveloper\n\nP",
        "Programmer\n\nDeveloper\n\nPr",
        "Programmer\n\nDeveloper\n\nPro",
        "Programmer\n\nDeveloper\n\nProb",
        "Programmer\n\nDeveloper\n\nProbl",
        "Programmer\n\nDeveloper\n\nProble",
        "Programmer\n\nDeveloper\n\nProblem",
        "Programmer\n\nDeveloper\n\nProblem S",
        "Programmer\n\nDeveloper\n\nProblem So",
        "Programmer\n\nDeveloper\n\nProblem Sol",
        "Programmer\n\nDeveloper\n\nProblem Solv",
        "Programmer\n\nDeveloper\n\nProblem Solve",
        "Programmer\n\nDeveloper\n\nProblem Solver"
    ];
    return message[index];
}